import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F4E8',
  },
  bookContainer: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    padding: 25,
    margin: 15,
    borderRadius: 15,
    shadowColor: '#8B4513',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    borderLeftWidth: 5,
    borderLeftColor: '#D4AF37',
  },
  bookImage: {
    width: 130,
    height: 195,
    borderRadius: 10,
    backgroundColor: '#E8DCC4',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 4,
  },
  bookInfo: {
    flex: 1,
    marginLeft: 20,
    justifyContent: 'center',
  },
  bookTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#4A3728',
    lineHeight: 28,
  },
  bookAuthor: {
    fontSize: 17,
    color: '#8B6F47',
    marginBottom: 20,
    fontStyle: 'italic',
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF9E6',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 25,
    alignSelf: 'flex-start',
  },
  star: {
    fontSize: 22,
    marginRight: 6,
  },
  averageText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#D4AF37',
  },
  ratingCount: {
    fontSize: 16,
    color: '#A0826D',
    marginLeft: 8,
  },
  section: {
    backgroundColor: '#FFF',
    padding: 25,
    marginHorizontal: 15,
    marginTop: 15,
    borderRadius: 15,
    shadowColor: '#8B4513',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 18,
    color: '#8B4513',
    borderBottomWidth: 2,
    borderBottomColor: '#D4AF37',
    paddingBottom: 10,
  },
  synopsis: {
    fontSize: 16,
    lineHeight: 25,
    color: '#5A4A3A',
  },
  ratingForm: {
    marginTop: 15,
  },
  label: {
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 12,
    color: '#8B4513',
  },
  starsRow: {
    flexDirection: 'row',
    marginBottom: 25,
    justifyContent: 'center',
  },
  starButton: {
    fontSize: 45,
    marginHorizontal: 3,
  },
  starDisplay: {
    fontSize: 32,
    marginRight: 5,
  },
  commentInput: {
    backgroundColor: '#FFF9E6',
    borderWidth: 2,
    borderColor: '#D4AF37',
    borderRadius: 12,
    padding: 18,
    fontSize: 16,
    height: 120,
    textAlignVertical: 'top',
    marginBottom: 20,
    color: '#4A3728',
  },
  submitButton: {
    backgroundColor: '#8B4513',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#8B4513',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  submitButtonText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  cancelButton: {
    marginTop: 12,
    padding: 15,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#8B4513',
    fontSize: 17,
    fontWeight: '600',
  },
  userRatingCard: {
    backgroundColor: '#FFF9E6',
    padding: 20,
    borderRadius: 12,
    marginTop: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#D4AF37',
  },
  userComment: {
    fontSize: 16,
    color: '#5A4A3A',
    marginTop: 12,
    marginBottom: 18,
    lineHeight: 24,
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  editButton: {
    flex: 1,
    backgroundColor: '#8B4513',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  editButtonText: {
    color: '#FFF',
    fontWeight: '700',
    fontSize: 15,
  },
  deleteButton: {
    flex: 1,
    backgroundColor: '#C44536',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  deleteButtonText: {
    color: '#FFF',
    fontWeight: '700',
    fontSize: 15,
  },
  ratingCard: {
    backgroundColor: '#FFF',
    padding: 20,
    borderRadius: 12,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#E8DCC4',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  ratingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  ratingUser: {
    fontSize: 17,
    fontWeight: '700',
    color: '#8B4513',
    textDecorationLine: 'underline',
  },
  starsRowSmall: {
    flexDirection: 'row',
  },
  starSmall: {
    fontSize: 16,
  },
  ratingComment: {
    fontSize: 16,
    color: '#5A4A3A',
    marginBottom: 12,
    lineHeight: 24,
  },
  ratingDate: {
    fontSize: 13,
    color: '#A0826D',
    fontStyle: 'italic',
  },
  noRatings: {
    textAlign: 'center',
    color: '#A0826D',
    fontSize: 17,
    padding: 30,
    fontStyle: 'italic',
  },
});

export default styles;
